---
title: "data visulization"
author: "YUjing Wang"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#crime over time

```{r}
crimes_clean %>%
group_by(offense, report_dat)%>%
dplyr::summarise(count = n()) %>%
ggplot(aes(x =report_dat, y = count ))+
geom_line(color ="#F2CA27" ,size = 0.1)+
geom_smooth(color = "1A1A1A")

```



```{r}
crimes_clean %>%
  group_by(hour,weekday) %>%
  drop_na(hour,weekday) %>%
  dplyr::summarise(count = n()) %>%
  ggplot(aes(x =as.factor(hour), y = weekday, fill = count, stat = "identity"))+
  geom_tile()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.6), legend.title = element_blank(), legend.position="top", legend.direction="horizontal", legend.key.width=unit(2, "cm"), legend.key.height=unit(0.25, "cm"), legend.margin=unit(-0.5,"cm"), panel.margin=element_blank())+
   labs(x = "Hour of Property Crime", y = "Day of Week of Property Crime", title = "Number of Property Crime in Dc from 2017 – 2022, by Time of Property Crime") +
  scale_fill_gradient(low = "white", high = "#27AE60", labels = comma)



```


#facet
```{r}
crimes_clean%>%
   filter(offense %in% crimes_clean$offense[2:19]) %>%
  group_by(offense,weekday,hour) %>% 
    drop_na(hour,weekday) %>%
  dplyr::summarise(count = n()) %>%
  
ggplot( aes(x = as.factor(hour), y = weekday, fill = count,stat = "identity")) +
  geom_tile()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.6, size = 4)) +
  labs(x = "Hour of Property Crime", y = "Day of Week of Property Crime", title = "Number of Property Crime in Washington DC from 2017 – 2021, by Category and Time of Property Crime") +
  scale_fill_gradient(low = "white", high = "#2980B9") +
  facet_wrap(~ offense, nrow = 2.5)

```