---
title: "Trend of crime against property during COVID"
author: "Peace Corp"
date: "4/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plyr)
library(dplyr)
library(readr)
library(purrr)
library(httr)
library(viridis)
library(lubridate)
library(hms)
library(janitor)
library(sf)
library(tidycensus)
library(dotenv)
library(patchwork)
#read and load DC crimes data
crimes <-
  list.files(path = "data/",
             pattern = "*.csv", 
             full.names = T) %>% 
  map_df(~read_csv(., col_types = cols("CCN"= col_double(),
                                       "LONGITUDE" = col_character(),
                                       "LATITUDE" = col_character()))) 
```


```{r}
#change case of the variables
change_case<-function(x){
  return(gsub("\\b([A-Z])([A-Z]+)", "\\U\\1\\L\\2", x, perl=TRUE))
}
#change case and split date variable to weekdays, month and year, label property offense 
crimes<-as.tibble(crimes)%>%
  clean_names()%>%
  dplyr::mutate(shift=change_case(shift),
                method=change_case(method),
                offense=change_case(offense),
                block=change_case(block),
                bid=change_case(bid),
                weekday=lubridate::wday((start_date), label=TRUE),
                month=lubridate::month((start_date),label=TRUE),
                year=lubridate::year(report_dat),
                occur_date=date(start_date),
                occur_time=hms::as_hms(ymd_hms(start_date)),
                hours=lubridate::hour(occur_time),
                crimetype=ifelse(offense%in%c("robbery","theft","burglary"), "property", "non-property")
  )
#
crimes_sf<-st_as_sf(crimes, coords = c("longitude", "latitude"),crs=4326)

#identify duplication incidents by CCN
crimes%>%
  group_by(ccn)%>%
  dplyr::mutate(count=n())%>%
  filter(count>1)
#remove duplicate rows 
crimes_clean<-filter(distinct(crimes, ccn, .keep_all = TRUE))
#check 
crimes_clean%>%
  group_by(ccn)%>%
  dplyr::mutate(count=n())%>%
  filter(count>1)

crimes_clean%>%
  group_by(offense)%>%
  dplyr::summarize(count=n())%>%
  arrange(desc(count))

crimes_clean %>% 
  group_by(offense) %>%
  dplyr::summarise(count=n())%>%
  ggplot(aes(x = reorder(offense,count), y=count, fill=offense))+
  geom_bar(stat="identity", width = 0.5, show.legend = FALSE)+
  geom_text(aes(label=count), vjust=2.5, size=3, colour = "black")+
  scale_fill_viridis(option = "D", discrete = T, direction = 1, begin = 0.9, end = 0.3) +
  theme_bw()+
  labs(x ="Offense", y = "Number of crimes", title = "Crimes in Washington D.C.") + 
  scale_y_continuous() +
  coord_flip()
```

```{r}
crimes_clean%>%
  group_by(offense, month)%>%
  dplyr::summarise(count = n())%>%
  ggplot(aes(x=month, y=count, color=offense))+
  geom_line(aes(group=offense))+
  geom_point()
```
```{r}
crimes_clean%>%
  group_by(hours, weekday)%>%
  dplyr::summarize(count=n())%>%
  ggplot(aes(x=hours, y=weekday, fill=count))+
  geom_tile()



```








```{r}
dc_census<-st_read("data/Census_Tracts_in_2020.shp")

crime_sf <-st_as_sf(crime_all, coords = c("longitude", "latitude"))
st_crs(crime_sf) <- 4326

ggplot(data = crime_sf) +
  geom_sf(data =dc_census,color="black") +theme_void()+
  geom_sf(data =crime_sf, aes(color=crimetype),alpha=0.2)+theme_void()
```

```{r}
#save the api key in a credential file
census_api_key("0f11197d613ca3de58c5217387d60ef938bd9a7b", install=TRUE, overwrite=TRUE)
v2019 <- load_variables(2019, "acs5", cache = TRUE)
credential<- Sys.getenv("census_api_key")
dc_population <- get_acs(geography = "tract",
                         variables = "B01003_001",
                         state = 11,
                         county = 001,
                         geometry = TRUE,
                         year = 2019,
                         progress = FALSE)
```
### API Census Track
```{r}
readRenviron("~/.Renviron")
credential<- Sys.getenv("census_api_key")
v2020 <- load_variables(2020, "acs5", cache = TRUE)


```


```{r}
#load the census tracts of chicago
unzip(zipfile="data/tl_2017_11_tract.zip",
      exdir = "data")
#read shapefile into sf
dc<-st_read("data/tl_2017_11_tract.shp")%>%
  select(GEOID, geometry)%>%
  clean_names()%>%
  st_transform(crs=4326)

crimes_sf<-st_as_sf(crimes_clean, coords = c("longitude", "latitude"),crs=4326)
  
#count the homicide and the arrest rate and perform a spatial join
dc_merged_agg<-st_join(dc, crimes_sf, join=st_intersects)%>%
  filter(year==2020, offense=="Theft F/Auto")%>%
  group_by(geoid)%>%
  dplyr::summarize(count = n())
#create choropleth of the count and arrest rate
count<-dc_merged_agg%>%
  ggplot()+
  geom_sf(aes(fill=count), color = "white", size = 0.1)

count
```
